### ISSUE TITLE
Djangoの構築

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/biz-matching#1]
### 目的

ソースコード管理をするために、DjangoをGithubへプッシュする。

### 完了要件

- [x] 初期状態のDjangoをプッシュ
- [x] Djangoのバージョンはv4.1

### 作業

- Python3系のインストール
- ローカル環境にDjangoをインストール
- DjangoとGithubを連携
- DjangoをGithubへプッシュ

### リンク

- [Django 公式ドキュメント](https://docs.djangoproject.com/ja/4.1/)

**Comment by potakai** [comment]
プッシュ完了しました！

**Comment by kmasuda1986** [comment]
@potakai 
README.md だけ？
https://github.com/RuckPlus/biz-matching

**Comment by kmasuda1986** [comment]
完了しましたのでクローズ致します。
