### ISSUE TITLE
プロジェクトの作成

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/biz-matching#2]
### 目的

プロジェクトの作成

### 完了要件

- [x] appディレクトリを作成する
- [x] `python manage.py runserver` でサーバーが立ち上がることを確認する

### hoge

```bash
biz-matching/
    manage.py
    app/
        __init__.py
        settings.py
        urls.py
        asgi.py
        wsgi.py
```

### リンク

[Django](https://docs.djangoproject.com/ja/4.1/intro/tutorial01/)

**Comment by potakai** [comment]
appディレクトリ作成とサーバー立ち上げ完了しました。pushしますか？

**Comment by kmasuda1986** [comment]
@potakai 
pushをお願いします！

**Comment by potakai** [comment]
@kmasuda1986 
pushしました！
