### ISSUE TITLE
Djangoの整理

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/biz-matching#3]
### 目的

開発効率を高めるために、Djangoを整理する。

masterブランチからfeature/#3ブランチを作成し、プルリクを作成してから作業を開始する。

### 完了要件

- [x] 指定のディレクトリ構成に変更されていること
- [x] `.gitignore` がどういう役割をしているか理解すること
- [x] `manage.py` がどういう役割をしているか理解すること
- [x] `requirements.txt` がどういう役割をしているか理解すること

### ディレクトリ構成

以下のディレクトリ構成になるように修正をお願いします。

```bash
# 修正後の構成
biz-matching
 ├ app/
 ├ .gitignore
 ├ README.md
 ├ manage.py
 ├ requirements.txt # 中身はなしでOK
 └ example.development.env # 中身はなしでOK
```

**Comment by potakai** [comment]
@kmasuda1986 
biz-matching
 ├ app/
 ├ .gitignore
 ├ README.md
 ├ manage.py
 ├ requirements.txt # 中身はなしでOK
 └ example.development.env # 中身はなしでOK

このディレクトリ以外は削除してもいいですか？
また、requirements.txtとexample.development.envはVScodeで空ファイルを作っただけですがターミナルでインストールしたほうがいいですか？

**Comment by kmasuda1986** [comment]
@potakai 
記載されていないファイナルやフォルダは削除でお願いします！

**Comment by kmasuda1986** [comment]
@potakai 
新しく作成していただいたファイルは、現時点では作成するだけで大丈夫です！

**Comment by kmasuda1986** [comment]
@potakai 
`.vscode` が消えていなかったみたいですが、こちらはクローズいたします。
