### ISSUE TITLE
基本設計書：画面一覧の作成

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/biz-matching#4]
### 概要

個人と個人をつなげるサービス、ビジネスマッチングアプリ

**機能**

- ログイン
- ユーザー一覧表示
- ユーザー検索
- プロフィール編集
- マッチング
- チャット

### 目的

開発する画面を把握するために、画面一覧を作成する。

[【基本設計書】画面設計書](https://docs.google.com/spreadsheets/d/1IhceuhguzbJ5TNIqZ4N_eltSzQNZ48KrVm1Q6MWowQU/edit?usp=share_link)

### 完了要件

- [x]  画面一覧を作成する

**Comment by potakai** [comment]
@kmasuda1986 一通り画面一覧作成してみました。確認お願いします！

**Comment by kmasuda1986** [comment]
@potakai 
めちゃくちゃ良い感じです！センスありますね！
こちらはクローズいたします。
