### ISSUE TITLE
製造：ログイン画面

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/biz-matching#8]
### 目的

ログイン画面を作成する。

### 完了要件

- [x] `urls.py` の理解ができていること
- [x] `views.py` の理解ができていること
- [x] `settings.py` の理解ができていること
- [x] `templates/index.html` が作成されていること
- [x] `app/settings.py` が修正されていること
- [x] `app/urls.py` が修正されていること
- [x] `user/uls.pt` が作成されていること
- [x] `user/views.py` が作成されていること

### HTMLサンプル

`templates/index.html` のサンプル。

```bash
<html>
<head>
<title>template test</title>
</head>
<body>
<p>This is {{app}} test.</p>
</body>
</html>
```

**Comment by potakai** [comment]
@kmasuda1986 
<img width="1792" alt="スクリーンショット 2022-11-06 20 10 58" src="https://user-images.githubusercontent.com/109352373/200167345-e7b5d155-36ca-4c56-ac55-e86de6809005.png">
アクセスできたんですが、http://127.0.0.1:8000/user/templates/ここまで打たないと表示されません。

**Comment by kmasuda1986** [comment]
@potakai 
これからソースコードを修正する作業があるときは、`master` ブランチ から `feature/#番号` ブランチを切って、プルリクを作成して作業をお願い致します！
`#番号` にあたる部分は、issueの番号でお願いします！

**Comment by kmasuda1986** [comment]
プルリクを作成したら、自分の好きなタイミングでプッシュをお願いします１

**Comment by kmasuda1986** [comment]
test

**Comment by potakai** [comment]
@kmasuda1986 
すみません今回ブランチ切るの忘れてました。。
承知しました！

**Comment by potakai** [comment]
@kmasuda1986 
masterブランチでプッシュしてしまったのでマージされてしまいましたが、確認お願いします！

**Comment by kmasuda1986** [comment]
@potakai 
確認できましたので、クローズ致します！
次のissueを考えるので少々お待ちください
