### ISSUE TITLE
user ディレクトリの整理

### ISSUE THREAD

**Issue by kmasuda1986** [RuckPlus/biz-matching#9]
### 目的

開発を進めていくために、user ディレクトリの構成を整える。

### 完了要件

- [x] `biz-matching/user/templates/web/base/base.html` が作成されていること
- [x] `biz-matching/user/templates/web/index.html` が作成されていること
- [x] `biz-matching/user/views/index.py` が作成されていること

### 補足

- `base.html` には、全画面共通で使えるようなHTMLを作成する
- `index.html` には、`base.html` を継承して `<body></body>` の中身だけを実装できるようにする
- `index.py` には、`return render(request, 'web/index.html')` のように、viewを返す関数を実装する

**Comment by potakai** [comment]
@kmasuda1986 
エラー解消したのでプルリク更新しました！

**Comment by kmasuda1986** [comment]
OK
